### ISSUE TITLE
adobjp[['OBJECTID', 'VALUE']] пустой

### ISSUE THREAD

**Issue by Ellariel** [nurtdinovadf/garbdfias#1]
На некоторых регионах из свежей выгрузки ГАР (88, 81, 82, 80, 84, 85) почему-то падает в блоке получения ОКТМО. Объект оказывается совсем пустой, без колонок..на этом месте:
adobjp = adobjp[['OBJECTID', 'VALUE']].rename( ##"None of [Index(['OBJECTID', 'VALUE'], dtype='object')] are in the [columns]"
    columns={'VALUE': 'OKTMO'}
).drop_duplicates().groupby(
    by='OBJECTID'
).agg(
    lambda x: x.to_list()
).to_dict('index')

UPD: Я тупой, эти регионы устарели :)

**Comment by Ellariel** [comment]
Это я тупой, таких регионов нет))

**Comment by nurtdinovadf** [comment]
насколько я помню (могу неправильно помнить), эти регионы (['80', '81', '82', '84', '85', '88']) падали, так как у них в объектах домов не было (пустые файлы либо неактуальные записи).

**Comment by Ellariel** [comment]
> насколько я помню (могу неправильно помнить), эти регионы (['80', '81', '82', '84', '85', '88']) падали, так как у них в объектах домов не было (пустые файлы либо неактуальные записи).

Да, спасибо! Понял это уже после того, как написал вопрос)
Может быть подскажете, как восстановить: нашёл несколько guid которые есть в hadobj, но по ним нет цепочек, а кажется должны быть, например в Адыгее: 1d2aa610-1553-49b6-99d2-4c65cda0868d (objid 1578), bc547a4e-042d-4fe9-ab42-bbb954a94437 (obj 1939). Видимо проблема в том, что там люди не живут и нет домов.. но поиск в ГАР на сайте ФНС показывает, что цепочка до НП вроде бы должна быть актуальной.. :'[

**Comment by Ellariel** [comment]
> 

нашёл где поправить :)

**Comment by nurtdinovadf** [comment]
@Ellariel  а рассказывать кто будет?

**Comment by Ellariel** [comment]
Цепочки в скрипте строятся от домиков (в этой логике уровень 10) и получается, там где нет домиков, нет и цепочек.. кажется, что упразднение этих двух фильтраций по уровню решает задачу:
for x in tqdm(adm0[adm0['LEVEL'] == '10']['PATH'])
for x in tqdm(hadobj[hadobj['LEVEL'] == '10']['OBJECTID'].drop_duplicates())
